### ISSUE TITLE
Is there any issue to switch back from Fish Shell?

### ISSUE THREAD

**Issue by simkimsia** [ghaiklor/iterm-fish-fisher-osx#11]
Hi there, 

currently using macOS catalina 

been using iterm2 and zsh for years

Found fishshell recently and looks intriguing googled fishshell vs zsh and your repo is one of the top Google results.

I would like to try your repo instructions. They look really good 👍 

Was wondering if I can switch back to zsh after trying out fishshell?

Can I have both fishshell and zsh running at the same time? Or I need to uninstall one of them? Is it possible to temporarily "mute" zsh and then try fish?

Thank you! Great repo by the way ❤️  it

**Comment by ghaiklor** [comment]
> Was wondering if I can switch back to zsh after trying out fishshell?

Yeah, you can easily switch between shells, no problems with that.

> Can I have both fishshell and zsh running at the same time?

Yes, you can have different shells running in different panes in terminal

> Or I need to uninstall one of them?

No, just install Fish and if you don’t like it you can either uninstall it or just switch default shell back to zsh

> Is it possible to temporarily "mute" zsh and then try fish?

That is what both my guides and script do. It will make all the preparations and just make Fish Shell the default shell of your computer. You can change it back to zsh whenever you want.

**Comment by ghaiklor** [comment]
Seems like I’ve answered the question, so closing this one.
