### ISSUE TITLE
Issue with the plugin thefuck

### ISSUE THREAD

**Issue by mcmxc** [ghaiklor/iterm-fish-fisher-osx#3]
Hey. Seems like something went wrong on my machine:
<img width="761" alt="screen shot 2017-12-24 at 23 02 16" src="https://user-images.githubusercontent.com/17690047/34329189-8aad892c-e8fe-11e7-87b7-8a1d59fe2f05.png">

What is the proper way to uninstall everything that was installed, to try again maybe.

**Comment by ghaiklor** [comment]
@mcmxc it's a known issue with the plugin `thefuck` - [KNOWN ISSUES](https://github.com/ghaiklor/iterm-fish-fisherman-osx/blob/master/KNOWN_ISSUES.md).

Just uninstall the plugin for Fish itself - `fisher rm thefuck` or try to fix that.
That is a floating bug that I couldn't reproduce on my machine, but some of my fellows also got the same.

They fixed this somehow by re-installing `thefuck` binaries and plugin manually.
