### ISSUE TITLE
fisherman

### ISSUE THREAD

**Issue by Nazar910** [ghaiklor/iterm-fish-fisher-osx#5]
https://github.com/jorgebucaran/fisher/issues/450

**Comment by Nazar910** [comment]
have fun 🍺

**Comment by ghaiklor** [comment]
Scripts were updated to reflect the new Fisherman API

**Comment by jorgebucaran** [comment]
Hi @ghaiklor! 👋  

Would you please rename ~~"fisherman"~~ to **"fisher"**. Fisher is the continuation of and successor to Fisherman. And could you also update your repository tags? 

<img width="900" alt="screen shot 2018-10-18 at 16 23 41" src="https://user-images.githubusercontent.com/56996/47137684-4cf76380-d2f2-11e8-8439-1945b45aa95a.png">


Cheers!

**Comment by jorgebucaran** [comment]
About changing the name of the repository; it is safe to do it. When you rename a repository, username or organization account, old links redirect to the new location. Changing the name of your repository will not result in broken-links.

See: https://blog.github.com/2013-05-16-repository-redirects-are-here/

**Comment by ghaiklor** [comment]
@jorgebucaran thanks for clarification, renamed all the occurrences to Fisher.

**Comment by jorgebucaran** [comment]
Cheers & thanks!

**Comment by jorgebucaran** [comment]
Awesome, thanks!

**Comment by BarbzYHOOL** [comment]
So fisherman repo is dead?

fisherman/tio disappeared

also where can we find the list of all plugins now? @jorgebucaran

**Comment by jorgebucaran** [comment]
@BarbzYHOOL Fisherman is now [Fisher](https://github.com/jorgebucaran/fisher).

> fisherman/tio disappeared

I made the repository private as I am rewriting it. I didn't have to do that, but that's what I did. I have 30~40 packages, which I am rewriting. It's going to take a while before everything goes back to normal.

> ...also where can we find the list of all plugins now? 

You mean packages, not plugins. See: [jorgebucaran/fisher/#483](https://github.com/jorgebucaran/fisher/pull/483) :)

---

If you have further questions, take them to [jorgebucaran/fisher/issues](https://github.com/jorgebucaran/fisher/issues). 👋

**Comment by BarbzYHOOL** [comment]
ok this is prob the most important one https://github.com/topics/fisherman

**Comment by jorgebucaran** [comment]
@BarbzYHOOL That's a lot of repositories. How can I get all these people to use the `fisher` tag instead.

**Comment by BarbzYHOOL** [comment]
I don't know, hence why it shouldn't have been disbanded imo...

Better use github API to automatically fork them somewhere or add them to a readme, no?

**Comment by jorgebucaran** [comment]
@BarbzYHOOL The tags are outdated because the project was renamed to Fisher. Disbanding the organization is unrelated to that.

I can knock at their door and ask them to update their tags. It's going to take some time, though.

**Comment by BarbzYHOOL** [comment]
at least put them in the awesome shell repo list (or accept the PR if I recall right)

**Comment by jorgebucaran** [comment]
@BarbzYHOOL The awesome-fish repo appears unmaintained because I am busy preparing the Fisher 3.2.0 release. After that, it'll get plenty of love. But if you send me a PR with that I can merge it (no open PRs at the time of this writing). 👋
