### ISSUE TITLE
my Iterm doesn't look like your example

### ISSUE THREAD

**Issue by faizalIPG** [ghaiklor/iterm-fish-fisher-osx#8]
@ghaiklor  I am following the Automatic Installation and it install everything with no issue. Once done I checked my iTerm and access to one of my project that have GIT inside it. so it should show my current branch which is **develop**. The weird thing is it doesn't show the current branch but it show the highlight red colour.

So my question is, is there any command that I can revert (uninstall) all and install it back?

**Comment by ghaiklor** [comment]
Hi @faizalIPG,

without screenshots and more information it is hard to say what have you faced. I'm guessing that it just tells you about dirty staging area:

<img width="639" alt="Screen Shot 2019-06-20 at 08 20 21" src="https://user-images.githubusercontent.com/3625244/59821787-4fec9d00-9334-11e9-963a-b0a3b3ebe01d.png">

1) Check `git status`, I believe that is the reason of red color
2) Default branches are not showed in terminal, like on screenshot above. It will show you branch name when you switch to non-default branch

**Comment by faizalIPG** [comment]
Hi @ghaiklor 
Here I attached a screenshot of my iTerm.

![image](https://user-images.githubusercontent.com/47510690/59826375-c7d4ba80-9368-11e9-82b2-13535933e987.png)
 I believed this is not about dirty staging. Do you have any idea why this happen? Is better you can provide me a command that can I revert (uninstall).

**Comment by faizalIPG** [comment]
Hi @ghaiklor 

I already fixed the issued. I need to update the **Font** and **Non-ASCII Font** in
Preference > Profiles > Text > Font / Non-ASCII Font

I changed the font to **Meslo**. now my iTerm look very nice.

![image](https://user-images.githubusercontent.com/47510690/59827209-a5dc3780-936a-11e9-9443-d8ff990b18c5.png)

thank you!

**Comment by ghaiklor** [comment]
@faizalIPG installer tells you to do that, but you didn't read what the software tells you, did you ? :)
happy it works for you

<img width="608" alt="Screen Shot 2019-06-20 at 10 10 22" src="https://user-images.githubusercontent.com/3625244/59828413-a44b4900-9343-11e9-8e5c-60fab5efe54c.png">

Unfortunately, I can not automize these kind of things and you need to switch to font with ligatures on your own

**Comment by faizalIPG** [comment]
I did, but it didn't said I need to add **Meslo**

**Comment by ghaiklor** [comment]
Oh, I got. Yeah, makes sense to say it there. I'll update it appropriately now.

**Comment by faizalIPG** [comment]
by the way, I really happy with what you did. It really amazing with only a single command it does everything and changed my iTerm style! thank you for the effort and surely I am happy with my iTerm now!  :)

**Comment by ghaiklor** [comment]
I'm glad :)

I really recommend you to get more familiar with plugins I'm setting up here (you can find them in README). It will make you more productive and faster, when working in terminal, IMHO.

And, JFYI, I've updated final messages, should be not confusing anymore:
https://github.com/ghaiklor/iterm-fish-fisher-osx/commit/0351b13995eb451fe1efbccddacaaeab4b728b6a
