### ISSUE TITLE
Using Manual install: Link to the font is broken

### ISSUE THREAD

**Issue by DeviousPenguin** [ghaiklor/iterm-fish-fisher-osx#9]
I'm using the Manual install method and the link to the font now seems broken:

https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/Meslo/M-DZ/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete%20Mono.otf

It looks like there is a similar file in the github repo for Nerd Fonts but it's a TTF file, would this work OK?

**Comment by ghaiklor** [comment]
@DeviousPenguin thanks for report. I have actual links in Bash script, you can use ones from there. In parallel I'll update links in guide.

Regard to font and color scheme, these are valid links

```shell
COLOR_SCHEME_URL="https://raw.githubusercontent.com/MartinSeeler/iterm2-material-design/master/material-design-colors.itermcolors"
NERD_FONT_URL="https://github.com/ryanoasis/nerd-fonts/blob/25eec835188d2316ef3fe59820950d9f90c5bcf4/patched-fonts/Meslo/M-DZ/Regular/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete%20Mono.ttf?raw=true"

```

**Comment by ghaiklor** [comment]
I've updated broken links in manual, thanks again

https://github.com/ghaiklor/iterm-fish-fisher-osx/commit/9787839d4447632efa780364bb476e24a04c2758

**Comment by DeviousPenguin** [comment]
No problem, thanks very much for fixing :)
